### ISSUE TITLE
docs: how to setup warpgate with mariadb/postgresql

### ISSUE THREAD

**Issue by ntimo** [warp-tech/warpgate#496]
# Description
Currently there are now docs for how to setup warpgate with mariadb/mysql or postgres.

# Desired solution
The docs should explain how to setup warpgate with mariadb and postgres.

**Comment by rolikeusch** [comment]
this [wiki](https://github.com/warp-tech/warpgate/wiki/Adding-a-MySQL-target)[](https://github.com/warp-tech/warpgate/wiki/Adding-a-MySQL-target) does not help for mysql/mariadb?
i'm not using db access in wargate 😉

**Comment by stappersg** [comment]
![afbeelding](https://user-images.githubusercontent.com/35434094/203805270-3f125b13-b888-4cf4-94a6-ee0367259646.png)

I think it should be edited, the blurred text says _"Not yet edited"_. The desired / needed edit explains that this issue is about internal database used by warpgate (**not** about warpgate database **targets**).

(
Text that will be deleted:
@ntimo consider to make a merge request that introduces a directory named `deploy`.
In that directory could be for starters the systemd unit file you wrote. Other text files in that documentation directory:
* deploy instruction
* instruction on configuring other database backend as the SQLite back (this issue)

)

**Comment by Eugeny** [comment]
@stappersg please refrain from any more passive-aggressive comments or you'll be blocked.

**Comment by Eugeny** [comment]
@ntimo updated the docs - the idea is to use `warpgate setup --database-url ...` with a `mysql://` or `postgres://` URL.

**Comment by ntimo** [comment]
Hey @Eugeny I just tested this and it does not seem to work I get this error when trying to setup warpgate with mysql:
```
The connection string 'mysql://warpgate:securepassword@localhost/warpgate' has no supporting driver
```

**Comment by Eugeny** [comment]
Are you compiling, using docker or the builds from the GitHub release?
________________________________

**Comment by ntimo** [comment]
I am using the binary from the Github release 0.7.0 for amd64 linux.

**Comment by ntimo** [comment]
Another not really related qustion but it seems like the database ids are a bit wiered :D 
```
MariaDB [warpgate]> select * from roles;
+------------------+----------------------+
| id               | name                 |
+------------------+----------------------+
| I�s诀I���� ��
                        | warp:ansible         |
| _�S<5L��YD(�t�8      | warpgate:admin       |
```

**Comment by Eugeny** [comment]
Thanks! I probably need to enable the corresponding crates features for the github build. The IDs are binary encoded UUIDs, so the mysql CLI probably can't display them.
