### ISSUE TITLE
PostgreSQL targets

### ISSUE THREAD

**Issue by thomasdba** [warp-tech/warpgate#938]
thanks

**Comment by Eugeny** [comment]
You can connect a PostgreSQL as a DB by setting `database_url: "postgres://host/db"` in the config file.

**Comment by Eugeny** [comment]
Sorry - I misread the title - yes, I'm planning to add Postgres support soon :)

**Comment by nosovk** [comment]
Cool, it would be nice to have PGSql as target

**Comment by flobaader** [comment]
@Eugeny are there already any updates on Postgres Support for Targets? That would be awesome!

**Comment by Eugeny** [comment]
No updates yet unfortunately as I haven't had time to work on it

**Comment by Eugeny** [comment]
There's now a very pre-alpha build available at https://nightly.link/warp-tech/warpgate/workflows/build/postgres

Pls note that it currently doesn't support SCRAM authentication between Warpgate and the target (between Warpgate and the client, only plaintext is supported because Warpgate hashes passwords in a way that is different from Postgres)
